webtalk_init -webtalk_dir C:/Users/adria/OneDrive - Vysok uen technick v Brn/Pota/DE1/Digitalelectronics-1/Labs07-ffs/flip_flops/flip_flops.sim/sim_1/behav/xsim/xsim.dir/tb_jk_ff_rst_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Mar 27 00:36:06 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f010f6b2-948d-4cd9-923f-dbb460f5db6a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "03fd2e9b63a1482ab4b9ad9d3b515796" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6544_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1313214966 -regid "" -xml C:/Users/adria/OneDrive - Vysok uen technick v Brn/Pota/DE1/Digitalelectronics-1/Labs07-ffs/flip_flops/flip_flops.sim/sim_1/behav/xsim/xsim.dir/tb_jk_ff_rst_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/adria/OneDrive - Vysok uen technick v Brn/Pota/DE1/Digitalelectronics-1/Labs07-ffs/flip_flops/flip_flops.sim/sim_1/behav/xsim/xsim.dir/tb_jk_ff_rst_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/adria/OneDrive - Vysok uen technick v Brn/Pota/DE1/Digitalelectronics-1/Labs07-ffs/flip_flops/flip_flops.sim/sim_1/behav/xsim/xsim.dir/tb_jk_ff_rst_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
